export default {
  login: "plvii",
  id: 88232630,
  node_id: "MDQ6VXNlcjg4MjMyNjMw",
  avatar_url: "https://avatars.githubusercontent.com/u/88232630?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/plvii",
  html_url: "https://github.com/plvii",
  followers_url: "https://api.github.com/users/plvii/followers",
  following_url: "https://api.github.com/users/plvii/following{/other_user}",
  gists_url: "https://api.github.com/users/plvii/gists{/gist_id}",
  starred_url: "https://api.github.com/users/plvii/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/plvii/subscriptions",
  organizations_url: "https://api.github.com/users/plvii/orgs",
  repos_url: "https://api.github.com/users/plvii/repos",
  events_url: "https://api.github.com/users/plvii/events{/privacy}",
  received_events_url: "https://api.github.com/users/plvii/received_events",
  type: "User",
  site_admin: false,
  name: "Pallavi Thakur",
  company: "NIT Silchar",
  blog: "",
  location: "Mandi (Himachal Pradesh)",
  email: null,
  hireable: null,
  bio: "Web Developer | CS Undergrad @NIT Silchar '24",
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-07-31T10:11:42Z",
  updated_at: "2023-07-24T10:11:02Z",
};
